name: environment
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  rxdart: ^0.27.2
  dio: ^4.0.4
  intl_phone_field: ^2.1.0
  bloc:
  flutter_bloc: ^7.2.0
  intl_phone_number_input: ^0.7.0+2
  currency_picker: ^2.0.5
  uuid: ^3.0.4
  percent_indicator: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  dropdown_search: ^2.0.1
  cross_connectivity: any
  flutter_pay: ^1.0.2
  mod97: ^1.0.0
  flutter_countdown_timer: ^4.1.0
  path_provider: ^2.0.6
  android_path_provider: ^0.3.0
  carousel_slider: ^4.0.0
  flutter_inappwebview: ^5.3.2
  device_info: ^2.0.2
  ios_utsname_ext: ^2.1.0
  permission_handler: ^8.2.5
  flutter_svg: ^0.22.0
  flutter_html: ^2.0.0
  #TODO SET Configurations IOS  https://pub.dev/packages/flutter_downloader
  flutter_downloader: ^1.7.1
  another_flushbar: ^1.10.24
  currency_text_input_formatter: ^2.1.5
  #TODO SET andriod setup
  file_picker: ^4.2.4
#  cryptography: ^2.0.5
#  cryptography_flutter: ^2.0.2
  #encrypt: ^5.0.1
  #FireBase Section
  #firebase_core: ^1.8.0
  #firebase_messaging: ^10.0.9
  #firebase_crashlytics: ^2.4.5
  flutter_notification_channel: ^2.0.0
  #timeago: ^3.1.0
  flutter_local_notifications: ^9.2.0
  webview_flutter: ^2.3.1
  pin_code_fields: ^7.3.0
  share: ^2.0.4
  url_launcher: ^6.0.17
  open_file: ^3.2.1
  flutter_secure_storage: ^5.0.2
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  flutter_background_service: ^1.0.4
  device_info_plus: ^3.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/splash/matron_spalsh.png"
  adaptive_icon_background: "#FFFFFF"
  adapptive_icon_foreground: "assets/images/splash/matron_spalsh.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/images/svg/
     - assets/images/splash/
     - assets/language/ar.json
     - assets/language/en.json
     - assets/images/matron_assets/ 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
    - family: frutiger-lt
      fonts:
        - asset: assets/fonts/frutiger-lt/FrutigerLTRoman.ttf
        - asset: assets/fonts/frutiger-lt/FrutigerLTArabic65Bold.ttf
    - family: MenuItem
      fonts:
        - asset: icons/MenuItem.ttf
    - family: CustomIcon
      fonts:
        - asset: icons/CustomIcon.ttf
    - family: File
      fonts:
        - asset: icons/File.ttf
    - family: IdentityFile
      fonts:
        - asset: icons/IdentityFile.ttf
    - family: Filenotification
      fonts:
        - asset: icons/Filenotification.ttf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
